
# Route 1: Authentication & User Service
spring.application.name=GATEWAY-SERVICE
server.port=8050

# Discovery Service (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Use Eureka discovery with lb:// scheme ---
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**
#spring.cloud.gateway.routes[0].predicates[1]=Path=/api/users/**

#spring.cloud.gateway.routes[0].predicates[1]=Path=/api/users/**

# Route 2: Course & Curriculum Service
spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=lb://COURSE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/programs/**,/api/courses/**,/api/modules/**,/api/progress/**
#spring.cloud.gateway.routes[1].predicates[1]=Path=/api/courses/**
#spring.cloud.gateway.routes[1].predicates[2]=Path=/api/modules/**

# Route 3: Enrollment Service
spring.cloud.gateway.routes[2].id=enrollment-service
spring.cloud.gateway.routes[2].uri=lb://ENROLLMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollments/**,/api/attendance/**

# Route 4: Content Service
spring.cloud.gateway.routes[3].id=content-service
spring.cloud.gateway.routes[3].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/content/**

# Route 5: Assessment Service
spring.cloud.gateway.routes[4].id=assessment-service
spring.cloud.gateway.routes[4].uri=lb://ASSESSMENT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/assessments/**,/api/quiz/**,/api/assessment/**,/api/submissions/**,/api/submission/**,/api/questions/**,/api/analysis/**

# ---------------------------------------------------------
# LOGGING
# ---------------------------------------------------------
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG